= Glossary

== Fediverse
A federation of independent social networks that allow users to interact with each other as if they were on a single platform.

More about it can be found at this https://de.wikipedia.org/wiki/Fediverse[Wikipedia Article].

== Node
An instance of a social network that is part of the Fediverse. It can consist of one or more processes.
The description of as node is independent of its implementation and is prefered for the description of the protocols used in this project.

== Other terms
Other terms can be found in the
https://www.informatik.htw-dresden.de/~hauptman/SEI/IEEE_Standard_Glossary_of_Software_Engineering_Terminology%20.pdf[IEEE Standard Glossary]
(link provided by the https://www.htwk-leipzig.de/[HTW Dresden])

== User
Someone who interacts with a Node.
If a user needs an account depends on the context just to be clear.

== Administrator
A "User" with administrative privileges on a Node.
The Administrator is responsible for the operation of the node and the data stored on it.

== Post
TODO...

== Member
TODO...