:pagesdir: pages

= Vision

== Einführung
Das Ziel dieses Dokuments ist es, die wesentlichen Bedarfe und Funktionalitäten für das Netzwerk zu sammeln, zu analysieren und zu definieren. Dieses Dokument dient als Grundlage für die weitere Entwicklung des Systems und die Erstellung der Anforderungsspezifikation.

=== Definitionen, Akronyme und Abkürzungen

Siehe <<glossary.adoc#Glossary, Glossary>>


== Positionierung

=== Motivation
//Erläutern Sie kurz den Hintergrund, in dem das Projekt angesiedelt ist. Welches Problem soll gelöst werden, wie ist es entstanden? Welche Verbesserung wird angestrebt. Achten Sie darauf, eine fachliche (organisatorische, betriebswirtschaftliche) Perspektive einzunehmen.
Dieses Projekt ermöglicht es unabhängigen Privatpersonen, Teil des Fedivers zu werden, indem die Grundlagen für ein dezentrales soziales Netzwerk geschaffen werden. Administratoren sollen in der Lage sein, einen Node einzurichten, zu pflegen und allgemein zu administrieren. 

Durch die Verwaltung der Nodes besteht die Möglichkeit für Administratoren, Werbung zu schalten und bei erfolgreicher Leistung ihres Knotens ein zusätzliches Einkommen zu generieren.

Dadurch wird es möglich, sich in Zukunft finanziell von großen Unternehmen unabhängig zu machen und nicht mehr auf ihre Regelwerke angewiesen zu sein.

Diese Unabhängigkeit ermöglicht es der Community, selbst darüber zu entscheiden, was als richtig erachtet wird und was nicht. Dies wirkt sich auch auf die Moderation aus, da sie nicht länger von einer einzelnen Instanz abhängig ist, sondern von der Gemeinschaft selbst gesteuert wird.

Die Community erhält die Befugnis, sowohl das Netzwerk als auch dessen Inhalte eigenständig zu verwalten. Sie kann selbst bestimmen, welche Inhalte sichtbar sein sollen und welche nicht. Auf diese Weise kann die Community das Wachstum und die Etablierung von Inhalten ähnlich wie in einem holokratischen System aktiv beeinflussen.

Es ist angestrebt, eine Plattform zu schaffen, die die Vielseitigkeit einer "Eierlegendewollmilchsau" besitzt, indem sie alle Funktionen aktueller sozialer Netzwerke vereint. Gleichzeitig soll jedoch die Flexibilität gewahrt bleiben, um viele verschiedene Nodes zu ermöglichen, die sich auf spezifische Funktionen spezialisieren können. Beispielsweise könnte es Nodes geben, die sich auf das Teilen von Bildern, Videos oder Texten fokussieren.

Diese modulare Struktur erlaubt es Benutzern, Nodes nach ihren individuellen Präferenzen zu wählen und zu betreiben. So kann jeder Nutzer seine Erfahrung personalisieren und sich auf die spezifischen Funktionen konzentrieren, die für ihn am relevantesten sind. Dieser Ansatz fördert eine differenzierte und maßgeschneiderte Nutzung des sozialen Netzwerks, während gleichzeitig die Gesamtfunktionalität einer umfassenden Plattform gewährleistet wird.

=== Problembeschreibung

[cols="1,3"]
|===
| Die Probleme | 
- Zentrale abhängigkeit von großen Unternehmen.

- Intranzparenz der Algorithmen.

- Exklusive Kontrolle über die Daten der Nutzer.

- Profitorientierte Unternehmen.

- Sepperate Accounts für verschiedene Plattformen.

- Interaktionen finden auf getrennten Plattformen statt.

| Betroffene | 
- Nutzer

- Administratoren 

- Außenstehende Personen 

| Auswirkungen | 

- Komplette Intranzparentz des Netzwerks

- Profitorintiertes Netzwerk

- Keine getrennte Überprüfung der Daten

| Eine erfolgreiche Lösung wäre | 

- Ein dezentrales Netzwerk, welches von der Community selbst verwaltet wird.

|===

=== Positionierung des Produkts

[cols="1,3"]
|===
| Wer? |
- Administratoren

| Wofür? |
- Verwaltung eines Nodes

| Lösung? |
- Eine Software mit allen Funktionen, welche für die Administration benötigt werden

| Unser Produkt |
- Ermöglicht es Administratoren, ein Node zu verwalten

|===

[cols="1,3"]
|===
| Wer? |
- User

| Wofür? |
- Nutzung des Netzwerkes

| Lösung? |
- Eine Software mit allen Funktionen, welche die Nutzung des Netzwerkes ermöglicht

| Unser Produkt |
- Ermöglicht es Nutzern, das Netzwerk zu nutzen

|===

=== Zusammenfassung der Produktstellung

//Fassen Sie die Positionierung des Produkts in einem Satz zusammen. Verwenden Sie dabei die folgende Vorlage: Für (Zielgruppe) die (Bedürfnis) haben, ist (Produktname) ein (Kategorie) das (Nutzen). Im Gegensatz zu (Wettbewerbsprodukt) bietet es (Unterscheidungsmerkmal).

Für Administratoren und Nutzern, die ein dezentrales soziales Netzwerk verwalten / nutzen wollen, ist Project-Rex ein Netzwerk, das von der Community selbst verwaltet wird. Im Gegensatz zu Facebook / Instagram / Discord und Co. bietet es eine dezentrale Struktur, die von der Community selbst verwaltet wird und alle Funktionalitäten in einer unabhängigen Plattform bündelt.


== Beschreibung der Stakeholder

=== Zusammenfassung der Stakeholder

[cols="1,2,2"]
|===

| Stakeholder | Beschreibung | Verantwortlichkeiten

| Nutzer | Personen, die das Netzwerk nutzen | Erstellung von Inhalten und Interaktion mit anderen Nutzern

| Administratoren | Personen, die ein Node administrieren | Verwaltung der Nodes

| Gesetzgeber | Personen, die Gesetze erlassen | Erlass von Gesetzen, welche die Privatsphäre der Nutzer schützen und die Verwaltung der Nodes regeln.

|===

=== Benutzerumgebung

==== Administratoren

1. Server mit Linux

2. Node wird auf einem Server installiert

3. Node wird konfiguriert

4. Node wird in Konsole administriert (zukünftig GUI)

==== Nutzer

1. Smartphone oder PC

2. App oder Website wird geöffnet

3. Nutzer erstellt Account / meldet sich an

4. Nutzer interagiert mit anderen Nutzern

=== Einschränkungen und Annahmen

==== Einschränkungen für Administratoren

- Die Software für Nodes wird vorerst nur für Linux entwickelt

- Die Software für Nodes wird für AMD und ARM Plattformen entwickelt

- Es wird am Anfang nur eine Konsole zur Administration der Nodes bereitgestellt

==== Einschränkungen für Nutzer

- Es wird eine App für Android / Apple bereitgestellt

- Es wird eine Website bereitgestellt

==== Annahmen

- Die Administratoren müssen fortgeschrittene Linux Kenntnisse besitzen

- Die Administratoren müssen fortgeschrittene Kenntnisse in der Administration von Servern besitzen

- Die Administratoren müssen fortgeschrittene Kenntnisse in der Administration von Netzwerken besitzen

- Die Administratoren müssen fortgeschrittene Kenntnisse in der Administration von Datenbanken besitzen

- Die Administratoren müssen fortgeschrittene Kenntnisse in der Administration von Webservern besitzen





=== Produkt-/Lösungsüberblick

==== Produkt-/Lösungsüberblick für Administratoren




==== Produkt-/Lösungsüberblick für Nutzer




==== Zusätzliche Produktanforderungen