//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "account"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: i64,
    pub email: String,
    pub email_verified: bool,
    pub active: bool,
    pub session_secret: Option<Vec<u8>>,
    pub admin: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Email,
    EmailVerified,
    Active,
    SessionSecret,
    Admin,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    LoginAttempt,
    Profile,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigInteger.def(),
            Self::Email => ColumnType::custom("citext").def().unique(),
            Self::EmailVerified => ColumnType::Boolean.def(),
            Self::Active => ColumnType::Boolean.def(),
            Self::SessionSecret => ColumnType::Binary(BlobSize::Blob(None)).def().null(),
            Self::Admin => ColumnType::Boolean.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::LoginAttempt => Entity::has_many(super::login_attempt::Entity).into(),
            Self::Profile => Entity::has_many(super::profile::Entity).into(),
        }
    }
}

impl Related<super::login_attempt::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoginAttempt.def()
    }
}

impl Related<super::profile::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Profile.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
