//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "attachment"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub post: i64,
    pub message: i64,
    pub comment: i64,
    pub asset: Vec<u8>,
    pub position: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Post,
    Message,
    Comment,
    Asset,
    Position,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Post,
    Message,
    Comment,
    Asset,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (i64, i64, i64, Vec<u8>);
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Asset,
    Comment,
    Message,
    Post,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Post => ColumnType::BigInteger.def(),
            Self::Message => ColumnType::BigInteger.def(),
            Self::Comment => ColumnType::BigInteger.def(),
            Self::Asset => ColumnType::Binary(BlobSize::Blob(None)).def(),
            Self::Position => ColumnType::Integer.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Asset => Entity::belongs_to(super::asset::Entity)
                .from(Column::Asset)
                .to(super::asset::Column::Checksum)
                .into(),
            Self::Comment => Entity::belongs_to(super::comment::Entity)
                .from(Column::Comment)
                .to(super::comment::Column::Id)
                .into(),
            Self::Message => Entity::belongs_to(super::message::Entity)
                .from(Column::Message)
                .to(super::message::Column::Id)
                .into(),
            Self::Post => Entity::belongs_to(super::post::Entity)
                .from(Column::Post)
                .to(super::post::Column::Id)
                .into(),
        }
    }
}

impl Related<super::asset::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Asset.def()
    }
}

impl Related<super::comment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Comment.def()
    }
}

impl Related<super::message::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Message.def()
    }
}

impl Related<super::post::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Post.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
