//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "comment"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: i64,
    pub author: i64,
    pub parent: Option<i64>,
    pub post: i64,
    pub created_at: DateTime,
    pub edited_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Author,
    Parent,
    Post,
    CreatedAt,
    EditedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Attachment,
    SelfRef,
    Post,
    Profile,
    UserPublicationReactionInteraction,
    UserPublicationsPreferenceInteraction,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigInteger.def(),
            Self::Author => ColumnType::BigInteger.def(),
            Self::Parent => ColumnType::BigInteger.def().null(),
            Self::Post => ColumnType::BigInteger.def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::EditedAt => ColumnType::DateTime.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Attachment => Entity::has_many(super::attachment::Entity).into(),
            Self::SelfRef => Entity::belongs_to(Entity)
                .from(Column::Parent)
                .to(Column::Id)
                .into(),
            Self::Post => Entity::belongs_to(super::post::Entity)
                .from(Column::Post)
                .to(super::post::Column::Id)
                .into(),
            Self::Profile => Entity::belongs_to(super::profile::Entity)
                .from(Column::Author)
                .to(super::profile::Column::Id)
                .into(),
            Self::UserPublicationReactionInteraction => {
                Entity::has_many(super::user_publication_reaction_interaction::Entity).into()
            }
            Self::UserPublicationsPreferenceInteraction => {
                Entity::has_many(super::user_publications_preference_interaction::Entity).into()
            }
        }
    }
}

impl Related<super::attachment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Attachment.def()
    }
}

impl Related<super::post::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Post.def()
    }
}

impl Related<super::profile::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Profile.def()
    }
}

impl Related<super::user_publication_reaction_interaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserPublicationReactionInteraction.def()
    }
}

impl Related<super::user_publications_preference_interaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserPublicationsPreferenceInteraction.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
