//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "channel_type")]
pub enum ChannelType {
    #[sea_orm(string_value = "announcement")]
    Announcement,
    #[sea_orm(string_value = "dummy")]
    Dummy,
    #[sea_orm(string_value = "feed")]
    Feed,
    #[sea_orm(string_value = "forum")]
    Forum,
    #[sea_orm(string_value = "stage")]
    Stage,
    #[sea_orm(string_value = "text")]
    Text,
    #[sea_orm(string_value = "voice")]
    Voice,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "user_preference")]
pub enum UserPreference {
    #[sea_orm(string_value = "dislike")]
    Dislike,
    #[sea_orm(string_value = "like")]
    Like,
}
