[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apalis = { version = "0.4.7", features = ["cron", "postgres"] }
tokio = { version = "1.34.0", features = ["full"] }
