name: Build
on:
  push:
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/build-pages.yaml'
      - 'pages/**'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.RUNS_ON }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - TARGET: 'x86_64-unknown-linux-gnu'
            RUNS_ON: 'ubuntu-latest'
          - TARGET: 'x86_64-pc-windows-msvc'
            RUNS_ON: 'windows-latest'
          - TARGET: 'x86_64-apple-darwin'
            RUNS_ON: 'macos-latest'
          - TARGET: 'aarch64-apple-darwin'
            RUNS_ON: 'macos-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.TARGET }}
          components: clippy
      - name: Build
        # TODO build all subprojects
        run: cargo build --target ${{ matrix.TARGET }}
      - name: Test
        run: cargo test --target ${{ matrix.TARGET }}
      - name: Benchmark
        run: cargo bench --target ${{ matrix.TARGET }}
      - name: Clippy
        run: cargo clippy --target ${{ matrix.TARGET }}

