on:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/build-pages.yaml'
      - 'pages/**'
jobs:
  build_pages:
    runs-on: ubuntu-latest
    name: Build Pages
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: actions/checkout@v4
        name: Setup Node.js
        with:
          node-version: 'latest'
          cache: 'yarn'
          cache-dependency-path: 'pages'
      - name: Install dependencies
        run: yarn install
        working-directory: pages
      - name: Build pages
        run: yarn build
        working-directory: pages
      - name: Archive pages
        uses: actions/upload-artifact@v3
        with:
          name: pages
          path: pages/build
          if-no-files-found: error

  build_docs:
    runs-on: ubuntu-latest
    name: Build Book
    container: asciidoctor/docker-asciidoctor
    env:
      PARAMS: "-r asciidoctor-diagram -r asciidoctor-mathematical"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build AsciiDoc (HTML)
        run: asciidoctor $PARAMS -o build/book.html book.adoc
        working-directory: docs
      - name: Build AsciiDoc (PDF)
        run: asciidoctor-pdf $PARAMS -o build/book.pdf book.adoc
        working-directory: docs
      - name: Archive Book
        uses: actions/upload-artifact@v3
        with:
          name: book
          path: docs/build/
          if-no-files-found: error



  publish_github_pages:
    concurrency:
      group: 'gh-pages'
      cancel-in-progress: true
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    needs:
      - build_pages
      - build_docs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download pages
        uses: actions/download-artifact@v2
        with:
          name: pages
          path: pages
      - name: Download book
        uses: actions/download-artifact@v2
        with:
          name: book
          path: pages/book
          if-no-files-found: error
      - name: Create Pages Archive
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          preview: true
          artifact-name: github-pages


